export enum PluginMessage {
  SAVE_PLUGIN_DATA = 'SAVE_PLUGIN_DATA',
  IS_INSTALLED = 'IS_INSTALLED',
  ACK_PLUGIN_INSTALL = 'ACK_PLUGIN_INSTALL',
  GET_PLUGIN_INFO = 'GET_PLUGIN_INFO',
  ACK_PLUGIN_DATA_SAVED = 'ACK_PLUGIN_DATA_SAVED',
}
