export enum DialogCommand {
  UNLOCK = 'UNLOCK',
  SEND_DIALOG_CONFIRM = 'sendDialogConfirm',
  SEND_DIALOG_ERROR = 'sendDialogError',
  REGISTER = 'register',
  BROADCASTING_WITHOUT_CONFIRMATION = 'broadcastingNoConfirm',
  WRONG_MK = 'WRONG_MK',
  ANSWER_REQUEST = 'answerRequest',
  READY = 'broadcastReady',
  SIGN_WITH_LEDGER = 'SIGN_WITH_LEDGER',
  RETURN_SIGNATURE = 'RETURN_SIGNATURE',
  RETURN_ERROR_SIGNING_TRANSACTION = 'RETURN_ERROR_SIGNING_TRANSACTION',
  REGISTER_KEYLESS_KEYCHAIN = 'REGISTER_KEYLESS_KEYCHAIN',
  ADD_ACCOUNT = 'ADD_ACCOUNT',
  PING = 'PING',
}

export enum MultisigDialogCommand {
  READY_MULTISIG = 'multisigReady',
  MULTISIG_SEND_DATA_TO_POPUP = 'MULTISIG_SEND_DATA_TO_POPUP',
}
