export enum LocalStorageKeyEnum {
  ACCOUNTS = 'accounts',
  RPC_LIST = 'rpc',
  CURRENT_RPC = 'current_rpc',
  ACTIVE_ACCOUNT_NAME = 'active_account_name',
  TRANSFER_TO_USERNAMES = 'transfer_to',
  KEYCHAINIFY_ENABLED = 'keychainify_enabled',
  CLAIM_REWARDS = 'claimRewards',
  CLAIM_ACCOUNTS = 'claimAccounts',
  AUTOLOCK = 'autolock',
  NO_CONFIRM = 'no_confirm',
  WALLET_HISTORY_FILTERS = 'walletHistoryFilters',
  HIDDEN_TOKENS = 'hidden_tokens',
  LOCAL_STORAGE_VERSION = 'LOCAL_STORAGE_VERSION',
}
