export enum Screen {
  ACCOUNT_PAGE_INIT_ACCOUNT = 'ACCOUNT_PAGE_INIT_ACCOUNT',
  ACCOUNT_PAGE_ADD_BY_KEYS = 'ACCOUNT_PAGE_ADD_BY_KEYS',
  ACCOUNT_PAGE_ADD_BY_AUTH = 'ACCOUNT_PAGE_ADD_BY_AUTH',
  ACCOUNT_PAGE_IMPORT_KEYS = 'ACCOUNT_PAGE_IMPORT_KEYS',
  ACCOUNT_PAGE_SELECT_KEYS = 'ACOUNT_PAGE_SELECT_KEYS',

  SIGN_IN_PAGE = 'SIGN_IN_PAGE',
  SIGN_UP_PAGE = 'SIGN_UP_PAGE',
  RESET_PASSWORD_PAGE = 'RESET_PASSWORD_PAGE',

  HOME_PAGE = 'HOME_PAGE',
  TRANSFER_FUND_PAGE = 'TRANSFER_FUND_PAGE',
  WITNESS_PAGE = 'WITNESS_PAGE',
  TOKENS_PAGE = 'TOKENS_PAGE',
  WALLET_HISTORY_PAGE = 'WALLET_HISTORY_PAGE',

  SETTINGS_ROUTER = 'SETTINGS_ROUTER',
  SETTINGS_MAIN_PAGE = 'SETTINGS_MAIN_PAGE',
}
