export enum Screen {
    ACCOUNT_PAGE_INIT_ACCOUNT = 'ACCOUNT_PAGE_INIT_ACCOUNT',
    ACCOUNT_PAGE_ADD_BY_KEYS = 'ACCOUNT_PAGE_ADD_BY_KEYS',
    ACCOUNT_PAGE_ADD_BY_AUTH = 'ACCOUNT_PAGE_ADD_BY_AUTH',
    ACCOUNT_PAGE_IMPORT_KEYS = 'ACCOUNT_PAGE_IMPORT_KEYS',
    SIGN_IN_PAGE = 'SIGN_IN_PAGE',
    SIGN_UP_PAGE = 'SIGN_UP_PAGE',
    HOME_PAGE = "HOME_PAGE"
    
}