export enum EvmActionType {
  SET_ACCOUNTS = 'SET_EVM_ACCOUNTS',

  // Active account
  SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT',
  SET_ACTIVE_ACCOUNT_HISTORY = 'SET_ACTIVE_ACCOUNT_HISTORY',
  SET_ACTIVE_ACCOUNT_TOKENS = 'SET_ACTIVE_ACCOUNT_TOKENS',
  SET_ACTIVE_ACCOUNT_NFT = 'SET_ACTIVE_ACCOUNT_NFT',

  SET_APP_STATUS = 'SET_APP_STATUS',
  RESET_APP_STATUS = 'RESET_APP_STATUS',

  SET_PRICES = 'SET_PRICES',
}
