export enum EvmActionType {
  SET_ACCOUNTS = 'SET_EVM_ACCOUNTS',
  SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT',

  SET_APP_STATUS = 'SET_APP_STATUS',
  RESET_APP_STATUS = 'RESET_APP_STATUS',

  SET_PRICES = 'SET_PRICES',
}
