export enum ActionType {
  TEST_MSG = 'TEST_MSG',
  SET_MK = 'SET_MK',

  GET_ACCOUNTS = 'GET_ACCOUNTS',
  ADD_ACCOUNT = 'ADD_ACCOUNT',
  SET_ACCOUNTS = 'SET_ACCOUNTS',
  RESET_ACCOUNT = 'RESET_ACCOUNT',

  SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE',
  NAVIGATE_TO = 'NAVIGATE_TO',
  NAVIGATE_TO_SECONDARY = 'NAVIGATE_TO_SECONDARY',
  NAVIGATE_TO_WITH_PARAMS = 'NAVIGATE_TO_WITH_PARAMS',
}
