//From this site:
//https://www.dnbcgroup.com/currency-converter/
//TODO: Move to commons

const countries = [
  {
    country: 'Afghanistan',
    country_code: 'AFG',
    country_code2: 'AF',
    currency_code: 'AFN',
    currency: 'Afghanistan Afghani',
  },
  {
    country: 'Albania',
    country_code: 'ALB',
    country_code2: 'AL',
    currency_code: 'ALL',
    currency: 'Albania Lek',
  },
  {
    country: 'Algeria',
    country_code: 'DZA',
    country_code2: 'DZ',
    currency_code: 'DZD',
    currency: '-',
  },
  {
    country: 'American Samoa',
    country_code: 'ASM',
    country_code2: 'AS',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Andorra',
    country_code: 'AND',
    country_code2: 'AD',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Angola',
    country_code: 'AGO',
    country_code2: 'AO',
    currency_code: 'AOA',
    currency: '-',
  },
  {
    country: 'Anguilla',
    country_code: 'AIA',
    country_code2: 'AI',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Antarctica',
    country_code: 'ATA',
    country_code2: 'AQ',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Antigua and Barbuda',
    country_code: 'ATG',
    country_code2: 'AG',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Argentina',
    country_code: 'ARG',
    country_code2: 'AR',
    currency_code: 'ARS',
    currency: 'Argentina Peso',
  },
  {
    country: 'Armenia',
    country_code: 'ARM',
    country_code2: 'AM',
    currency_code: 'AMD',
    currency: '-',
  },
  {
    country: 'Aruba',
    country_code: 'ABW',
    country_code2: 'AW',
    currency_code: 'AWG',
    currency: 'Aruba Guilder',
  },
  {
    country: 'Australia',
    country_code: 'AUS',
    country_code2: 'AU',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'Austria',
    country_code: 'AUT',
    country_code2: 'AT',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Azerbaijan',
    country_code: 'AZE',
    country_code2: 'AZ',
    currency_code: 'AZN',
    currency: 'Azerbaijan Manat',
  },
  {
    country: 'Bahamas',
    country_code: 'BHS',
    country_code2: 'BS',
    currency_code: 'BSD',
    currency: 'Bahamas Dollar',
  },
  {
    country: 'Bahrain',
    country_code: 'BHR',
    country_code2: 'BH',
    currency_code: 'BHD',
    currency: '-',
  },
  {
    country: 'Bangladesh',
    country_code: 'BGD',
    country_code2: 'BD',
    currency_code: 'BDT',
    currency: '-',
  },
  {
    country: 'Barbados',
    country_code: 'BRB',
    country_code2: 'BB',
    currency_code: 'BBD',
    currency: 'Barbados Dollar',
  },
  {
    country: 'Belarus',
    country_code: 'BLR',
    country_code2: 'BY',
    currency_code: 'BYN',
    currency: 'Belarus Ruble',
  },
  {
    country: 'Belgium',
    country_code: 'BEL',
    country_code2: 'BE',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Belize',
    country_code: 'BLZ',
    country_code2: 'BZ',
    currency_code: 'BZD',
    currency: 'Belize Dollar',
  },
  {
    country: 'Benin',
    country_code: 'BEN',
    country_code2: 'BJ',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Bermuda',
    country_code: 'BMU',
    country_code2: 'BM',
    currency_code: 'BMD',
    currency: 'Bermuda Dollar',
  },
  {
    country: 'Bhutan',
    country_code: 'BTN',
    country_code2: 'BT',
    currency_code: 'INR',
    currency: 'India Rupee',
  },
  {
    country: 'Bolivia',
    country_code: 'BOL',
    country_code2: 'BO',
    currency_code: 'BOB',
    currency: 'Bolivia Bolíviano',
  },
  {
    country: 'Bosnia and Herzegovina',
    country_code: 'BIH',
    country_code2: 'BA',
    currency_code: 'BAM',
    currency:
      'Bosnia and Herzegovina Convertible Mark                                          ',
  },
  {
    country: 'Botswana',
    country_code: 'BWA',
    country_code2: 'BW',
    currency_code: 'BWP',
    currency: 'Botswana Pula',
  },
  {
    country: 'Bouvet Island',
    country_code: 'BVT',
    country_code2: 'BV',
    currency_code: 'NOK',
    currency: 'Norway Krone',
  },
  {
    country: 'Brazil',
    country_code: 'BRA',
    country_code2: 'BR',
    currency_code: 'BRL',
    currency: 'Brazil Real',
  },
  {
    country: 'British Indian Ocean Territory',
    country_code: 'IOT',
    country_code2: 'IO',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'British Virgin Islands',
    country_code: 'VGB',
    country_code2: 'VG',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Brunei',
    country_code: 'BRN',
    country_code2: 'BN',
    currency_code: 'BND',
    currency: 'Brunei Darussalam Dollar',
  },
  {
    country: 'Bulgaria',
    country_code: 'BGR',
    country_code2: 'BG',
    currency_code: 'BGN',
    currency: 'Bulgaria Lev',
  },
  {
    country: 'Burkina Faso',
    country_code: 'BFA',
    country_code2: 'BF',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Burundi',
    country_code: 'BDI',
    country_code2: 'BI',
    currency_code: 'BIF',
    currency: '-',
  },
  {
    country: 'Cambodia',
    country_code: 'KHM',
    country_code2: 'KH',
    currency_code: 'KHR',
    currency: 'Cambodia Riel',
  },
  {
    country: 'Cameroon',
    country_code: 'CMR',
    country_code2: 'CM',
    currency_code: 'XAF',
    currency: '-',
  },
  {
    country: 'Canada',
    country_code: 'CAN',
    country_code2: 'CA',
    currency_code: 'CAD',
    currency: 'Canada Dollar',
  },
  {
    country: 'Cape Verde',
    country_code: 'CPV',
    country_code2: 'CV',
    currency_code: 'CVE',
    currency: '-',
  },
  {
    country: 'Cayman Islands',
    country_code: 'CYM',
    country_code2: 'KY',
    currency_code: 'KYD',
    currency: 'Cayman Islands Dollar',
  },
  {
    country: 'Central African Republic',
    country_code: 'CAF',
    country_code2: 'CF',
    currency_code: 'XAF',
    currency: '-',
  },
  {
    country: 'Chad',
    country_code: 'TCD',
    country_code2: 'TD',
    currency_code: 'XAF',
    currency: '-',
  },
  {
    country: 'Chile',
    country_code: 'CHL',
    country_code2: 'CL',
    currency_code: 'CLP',
    currency: 'Chile Peso',
  },
  {
    country: 'China',
    country_code: 'CHN',
    country_code2: 'CN',
    currency_code: 'CNY',
    currency: 'China Yuan Renminbi',
  },
  {
    country: 'Christmas Island',
    country_code: 'CXR',
    country_code2: 'CX',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'Colombia',
    country_code: 'COL',
    country_code2: 'CO',
    currency_code: 'COP',
    currency: 'Colombia Peso',
  },
  {
    country: 'Comoros',
    country_code: 'COM',
    country_code2: 'KM',
    currency_code: 'KMF',
    currency: '-',
  },
  {
    country: 'Cook Islands',
    country_code: 'COK',
    country_code2: 'CK',
    currency_code: 'NZD',
    currency: 'New Zealand Dollar',
  },
  {
    country: 'Costa Rica',
    country_code: 'CRI',
    country_code2: 'CR',
    currency_code: 'CRC',
    currency: 'Costa Rica Colon',
  },
  {
    country: 'Croatia',
    country_code: 'HRV',
    country_code2: 'HR',
    currency_code: 'HRK',
    currency: 'Croatia Kuna',
  },
  {
    country: 'Cuba',
    country_code: 'CUB',
    country_code2: 'CU',
    currency_code: 'CUP',
    currency: 'Cuba Peso',
  },
  {
    country: 'Cyprus',
    country_code: 'CYP',
    country_code2: 'CY',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Czech Republic',
    country_code: 'CZE',
    country_code2: 'CZ',
    currency_code: 'CZK',
    currency: 'Czech Republic Koruna',
  },
  {
    country: 'Congo - Kinshasa',
    country_code: 'COD',
    country_code2: 'CD',
    currency_code: 'CDF',
    currency: '-',
  },
  {
    country: 'Denmark',
    country_code: 'DNK',
    country_code2: 'DK',
    currency_code: 'DKK',
    currency: 'Denmark Krone',
  },
  {
    country: 'Djibouti',
    country_code: 'DJI',
    country_code2: 'DJ',
    currency_code: 'DJF',
    currency: '-',
  },
  {
    country: 'Dominica',
    country_code: 'DMA',
    country_code2: 'DM',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Dominican Republic',
    country_code: 'DOM',
    country_code2: 'DO',
    currency_code: 'DOP',
    currency: 'Dominican Republic Peso',
  },
  {
    country: 'East Timor',
    country_code: 'TLS',
    country_code2: 'TL',
    currency_code: 'IDR',
    currency: 'Indonesia Rupiah',
  },
  {
    country: 'Ecuador',
    country_code: 'ECU',
    country_code2: 'EC',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Egypt',
    country_code: 'EGY',
    country_code2: 'EG',
    currency_code: 'EGP',
    currency: 'Egypt Pound',
  },
  {
    country: 'El Salvador',
    country_code: 'SLV',
    country_code2: 'SV',
    currency_code: 'SVC',
    currency: 'El Salvador Colon',
  },
  {
    country: 'Equatorial Guinea',
    country_code: 'GNQ',
    country_code2: 'GQ',
    currency_code: 'XAF',
    currency: '-',
  },
  {
    country: 'Eritrea',
    country_code: 'ERI',
    country_code2: 'ER',
    currency_code: 'ERN',
    currency: '-',
  },
  {
    country: 'Estonia',
    country_code: 'EST',
    country_code2: 'EE',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Ethiopia',
    country_code: 'ETH',
    country_code2: 'ET',
    currency_code: 'ETB',
    currency: '-',
  },
  {
    country: 'Falkland Islands',
    country_code: 'FLK',
    country_code2: 'FK',
    currency_code: 'FKP',
    currency: 'Falkland Islands (Malvinas) Pound',
  },
  {
    country: 'Faroe Islands',
    country_code: 'FRO',
    country_code2: 'FO',
    currency_code: 'DKK',
    currency: 'Denmark Krone',
  },
  {
    country: 'Fiji',
    country_code: 'FJI',
    country_code2: 'FJ',
    currency_code: 'FJD',
    currency: 'Fiji Dollar',
  },
  {
    country: 'Finland',
    country_code: 'FIN',
    country_code2: 'FI',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'France',
    country_code: 'FRA',
    country_code2: 'FR',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'French Guiana',
    country_code: 'GUF',
    country_code2: 'GF',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'French Polynesia',
    country_code: 'PYF',
    country_code2: 'PF',
    currency_code: 'XPF',
    currency: '-',
  },
  {
    country: 'French Southern Territories',
    country_code: 'ATF',
    country_code2: 'TF',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Gabon',
    country_code: 'GAB',
    country_code2: 'GA',
    currency_code: 'XAF',
    currency: '-',
  },
  {
    country: 'Gambia',
    country_code: 'GMB',
    country_code2: 'GM',
    currency_code: 'GMD',
    currency: '-',
  },
  {
    country: 'Georgia',
    country_code: 'GEO',
    country_code2: 'GE',
    currency_code: 'GEL',
    currency: '-',
  },
  {
    country: 'Germany',
    country_code: 'DEU',
    country_code2: 'DE',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Ghana',
    country_code: 'GHA',
    country_code2: 'GH',
    currency_code: 'GHS',
    currency: 'Ghana Cedi',
  },
  {
    country: 'Gibraltar',
    country_code: 'GIB',
    country_code2: 'GI',
    currency_code: 'GIP',
    currency: 'Gibraltar Pound',
  },
  {
    country: 'Greece',
    country_code: 'GRC',
    country_code2: 'GR',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Greenland',
    country_code: 'GRL',
    country_code2: 'GL',
    currency_code: 'DKK',
    currency: 'Denmark Krone',
  },
  {
    country: 'Grenada',
    country_code: 'GRD',
    country_code2: 'GD',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Guadeloupe',
    country_code: 'GLP',
    country_code2: 'GP',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Guam',
    country_code: 'GUM',
    country_code2: 'GU',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Guatemala',
    country_code: 'GTM',
    country_code2: 'GT',
    currency_code: 'GTQ',
    currency: 'Guatemala Quetzal',
  },
  {
    country: 'Guinea',
    country_code: 'GIN',
    country_code2: 'GN',
    currency_code: 'GNF',
    currency: '-',
  },
  {
    country: 'Guinea-Bissau',
    country_code: 'GNB',
    country_code2: 'GW',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Guyana',
    country_code: 'GUY',
    country_code2: 'GY',
    currency_code: 'GYD',
    currency: 'Guyana Dollar',
  },
  {
    country: 'Haiti',
    country_code: 'HTI',
    country_code2: 'HT',
    currency_code: 'HTG',
    currency: '-',
  },
  {
    country: 'Heard Island and McDonald Islands',
    country_code: 'HMD',
    country_code2: 'HM',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'Honduras',
    country_code: 'HND',
    country_code2: 'HN',
    currency_code: 'HNL',
    currency: 'Honduras Lempira',
  },
  {
    country: 'Hong Kong',
    country_code: 'HKG',
    country_code2: 'HK',
    currency_code: 'HKD',
    currency: 'Hong Kong Dollar',
  },
  {
    country: 'Hungary',
    country_code: 'HUN',
    country_code2: 'HU',
    currency_code: 'HUF',
    currency: 'Hungary Forint',
  },
  {
    country: 'Iceland',
    country_code: 'ISL',
    country_code2: 'IS',
    currency_code: 'ISK',
    currency: 'Iceland Krona',
  },
  {
    country: 'India',
    country_code: 'IND',
    country_code2: 'IN',
    currency_code: 'INR',
    currency: 'India Rupee',
  },
  {
    country: 'Indonesia',
    country_code: 'IDN',
    country_code2: 'ID',
    currency_code: 'IDR',
    currency: 'Indonesia Rupiah',
  },
  {
    country: 'Iran',
    country_code: 'IRN',
    country_code2: 'IR',
    currency_code: 'IRR',
    currency: 'Iran Rial',
  },
  {
    country: 'Iraq',
    country_code: 'IRQ',
    country_code2: 'IQ',
    currency_code: 'IQD',
    currency: '-',
  },
  {
    country: 'Ireland',
    country_code: 'IRL',
    country_code2: 'IE',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Israel',
    country_code: 'ISR',
    country_code2: 'IL',
    currency_code: 'ILS',
    currency: 'Israel Shekel',
  },
  {
    country: 'Italy',
    country_code: 'ITA',
    country_code2: 'IT',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Côte d’Ivoire',
    country_code: 'CIV',
    country_code2: 'CI',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Jamaica',
    country_code: 'JAM',
    country_code2: 'JM',
    currency_code: 'JMD',
    currency: 'Jamaica Dollar',
  },
  {
    country: 'Japan',
    country_code: 'JPN',
    country_code2: 'JP',
    currency_code: 'JPY',
    currency: 'Japan Yen',
  },
  {
    country: 'Jordan',
    country_code: 'JOR',
    country_code2: 'JO',
    currency_code: 'JOD',
    currency: '-',
  },
  {
    country: 'Kazakhstan',
    country_code: 'KAZ',
    country_code2: 'KZ',
    currency_code: 'KZT',
    currency: 'Kazakhstan Tenge',
  },
  {
    country: 'Kenya',
    country_code: 'KEN',
    country_code2: 'KE',
    currency_code: 'KES',
    currency: '-',
  },
  {
    country: 'Kiribati',
    country_code: 'KIR',
    country_code2: 'KI',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'Kuwait',
    country_code: 'KWT',
    country_code2: 'KW',
    currency_code: 'KWD',
    currency: '-',
  },
  {
    country: 'Kyrgyzstan',
    country_code: 'KGZ',
    country_code2: 'KG',
    currency_code: 'KGS',
    currency: 'Kyrgyzstan Som',
  },
  {
    country: 'Laos',
    country_code: 'LAO',
    country_code2: 'LA',
    currency_code: 'LAK',
    currency: 'Laos Kip',
  },
  {
    country: 'Latvia',
    country_code: 'LVA',
    country_code2: 'LV',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Lebanon',
    country_code: 'LBN',
    country_code2: 'LB',
    currency_code: 'LBP',
    currency: 'Lebanon Pound',
  },
  {
    country: 'Lesotho',
    country_code: 'LSO',
    country_code2: 'LS',
    currency_code: 'LSL',
    currency: '-',
  },
  {
    country: 'Liberia',
    country_code: 'LBR',
    country_code2: 'LR',
    currency_code: 'LRD',
    currency: 'Liberia Dollar',
  },
  {
    country: 'Libya',
    country_code: 'LBY',
    country_code2: 'LY',
    currency_code: 'LYD',
    currency: '-',
  },
  {
    country: 'Liechtenstein',
    country_code: 'LIE',
    country_code2: 'LI',
    currency_code: 'CHF',
    currency: 'Switzerland Franc',
  },
  {
    country: 'Lithuania',
    country_code: 'LTU',
    country_code2: 'LT',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Luxembourg',
    country_code: 'LUX',
    country_code2: 'LU',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Macau',
    country_code: 'MAC',
    country_code2: 'MO',
    currency_code: 'MOP',
    currency: '-',
  },
  {
    country: 'Macedonia',
    country_code: 'MKD',
    country_code2: 'MK',
    currency_code: 'MKD',
    currency: 'Macedonia Denar',
  },
  {
    country: 'Madagascar',
    country_code: 'MDG',
    country_code2: 'MG',
    currency_code: 'MGA',
    currency: '-',
  },
  {
    country: 'Malawi',
    country_code: 'MWI',
    country_code2: 'MW',
    currency_code: 'MWK',
    currency: '-',
  },
  {
    country: 'Malaysia',
    country_code: 'MYS',
    country_code2: 'MY',
    currency_code: 'MYR',
    currency: 'Malaysia Ringgit',
  },
  {
    country: 'Maldives',
    country_code: 'MDV',
    country_code2: 'MV',
    currency_code: 'MVR',
    currency: '-',
  },
  {
    country: 'Mali',
    country_code: 'MLI',
    country_code2: 'ML',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Malta',
    country_code: 'MLT',
    country_code2: 'MT',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Marshall Islands',
    country_code: 'MHL',
    country_code2: 'MH',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Martinique',
    country_code: 'MTQ',
    country_code2: 'MQ',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Mauritania',
    country_code: 'MRT',
    country_code2: 'MR',
    currency_code: 'MRU',
    currency: '-',
  },
  {
    country: 'Mauritius',
    country_code: 'MUS',
    country_code2: 'MU',
    currency_code: 'MUR',
    currency: 'Mauritius Rupee',
  },
  {
    country: 'Mayotte',
    country_code: 'MYT',
    country_code2: 'YT',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Mexico',
    country_code: 'MEX',
    country_code2: 'MX',
    currency_code: 'MXN',
    currency: 'Mexico Peso',
  },
  {
    country: 'Micronesia',
    country_code: 'FSM',
    country_code2: 'FM',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Moldova',
    country_code: 'MDA',
    country_code2: 'MD',
    currency_code: 'MDL',
    currency: '-',
  },
  {
    country: 'Monaco',
    country_code: 'MCO',
    country_code2: 'MC',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Mongolia',
    country_code: 'MNG',
    country_code2: 'MN',
    currency_code: 'MNT',
    currency: 'Moroccan-dirham',
  },
  {
    country: 'Montserrat',
    country_code: 'MSR',
    country_code2: 'MS',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Morocco',
    country_code: 'MAR',
    country_code2: 'MA',
    currency_code: 'MAD',
    currency: '-',
  },
  {
    country: 'Mozambique',
    country_code: 'MOZ',
    country_code2: 'MZ',
    currency_code: 'MZN',
    currency: 'Mozambique Metical',
  },
  {
    country: 'Myanmar',
    country_code: 'MMR',
    country_code2: 'MM',
    currency_code: 'MMK',
    currency: '-',
  },
  {
    country: 'Namibia',
    country_code: 'NAM',
    country_code2: 'NA',
    currency_code: 'NAD',
    currency: 'Namibia Dollar',
  },
  {
    country: 'Nauru',
    country_code: 'NRU',
    country_code2: 'NR',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'Nepal',
    country_code: 'NPL',
    country_code2: 'NP',
    currency_code: 'NPR',
    currency: 'Nepal Rupee',
  },
  {
    country: 'Netherlands',
    country_code: 'NLD',
    country_code2: 'NL',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Netherlands Antilles',
    country_code: 'ANT',
    country_code2: 'AN',
    currency_code: 'ANG',
    currency: 'Netherlands Antilles Guilder',
  },
  {
    country: 'New Caledonia',
    country_code: 'NCL',
    country_code2: 'NC',
    currency_code: 'XPF',
    currency: '-',
  },
  {
    country: 'New Zealand',
    country_code: 'NZL',
    country_code2: 'NZ',
    currency_code: 'NZD',
    currency: 'New Zealand Dollar',
  },
  {
    country: 'Nicaragua',
    country_code: 'NIC',
    country_code2: 'NI',
    currency_code: 'NIO',
    currency: 'Nicaragua Cordoba',
  },
  {
    country: 'Niger',
    country_code: 'NER',
    country_code2: 'NE',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Nigeria',
    country_code: 'NGA',
    country_code2: 'NG',
    currency_code: 'NGN',
    currency: 'Nigeria Naira',
  },
  {
    country: 'Niue',
    country_code: 'NIU',
    country_code2: 'NU',
    currency_code: 'NZD',
    currency: 'New Zealand Dollar',
  },
  {
    country: 'Norfolk Island',
    country_code: 'NFK',
    country_code2: 'NF',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'North Korea',
    country_code: 'PRK',
    country_code2: 'KP',
    currency_code: 'KPW',
    currency: 'Korea (North) Won',
  },
  {
    country: 'Northern Mariana Islands',
    country_code: 'MNP',
    country_code2: 'MP',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Norway',
    country_code: 'NOR',
    country_code2: 'NO',
    currency_code: 'NOK',
    currency: 'Norway Krone',
  },
  {
    country: 'Oman',
    country_code: 'OMN',
    country_code2: 'OM',
    currency_code: 'OMR',
    currency: 'Oman Rial',
  },
  {
    country: 'Pakistan',
    country_code: 'PAK',
    country_code2: 'PK',
    currency_code: 'PKR',
    currency: 'Pakistan Rupee',
  },
  {
    country: 'Palau',
    country_code: 'PLW',
    country_code2: 'PW',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Palestine',
    country_code: 'PSE',
    country_code2: 'PS',
    currency_code: 'JOD',
    currency: '-',
  },
  {
    country: 'Panama',
    country_code: 'PAN',
    country_code2: 'PA',
    currency_code: 'PAB',
    currency: 'Panama Balboa',
  },
  {
    country: 'Papua New Guinea',
    country_code: 'PNG',
    country_code2: 'PG',
    currency_code: 'PGK',
    currency: '-',
  },
  {
    country: 'Paraguay',
    country_code: 'PRY',
    country_code2: 'PY',
    currency_code: 'PYG',
    currency: 'Paraguay Guarani',
  },
  {
    country: 'Peru',
    country_code: 'PER',
    country_code2: 'PE',
    currency_code: 'PEN',
    currency: 'Peru Sol',
  },
  {
    country: 'Philippines',
    country_code: 'PHL',
    country_code2: 'PH',
    currency_code: 'PHP',
    currency: 'Philippines Peso',
  },
  {
    country: 'Pitcairn',
    country_code: 'PCN',
    country_code2: 'PN',
    currency_code: 'NZD',
    currency: 'New Zealand Dollar',
  },
  {
    country: 'Poland',
    country_code: 'POL',
    country_code2: 'PL',
    currency_code: 'PLN',
    currency: 'Poland Zloty',
  },
  {
    country: 'Portugal',
    country_code: 'PRT',
    country_code2: 'PT',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Puerto Rico',
    country_code: 'PRI',
    country_code2: 'PR',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Qatar',
    country_code: 'QAT',
    country_code2: 'QA',
    currency_code: 'QAR',
    currency: 'Qatar Riyal',
  },
  {
    country: 'Congo - Brazzaville',
    country_code: 'COG',
    country_code2: 'CG',
    currency_code: 'XAF',
    currency: '-',
  },
  {
    country: 'Reunion',
    country_code: 'REU',
    country_code2: 'RE',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Romania',
    country_code: 'ROU',
    country_code2: 'RO',
    currency_code: 'RON',
    currency: 'Romania Leu',
  },
  {
    country: 'Rwanda',
    country_code: 'RWA',
    country_code2: 'RW',
    currency_code: 'RWF',
    currency: '-',
  },
  {
    country: 'Saint Helena',
    country_code: 'SHN',
    country_code2: 'SH',
    currency_code: 'GBP',
    currency: 'United Kingdom Pound',
  },
  {
    country: 'Saint Kitts and Nevis',
    country_code: 'KNA',
    country_code2: 'KN',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Saint Lucia',
    country_code: 'LCA',
    country_code2: 'LC',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Saint Pierre and Miquelon',
    country_code: 'SPM',
    country_code2: 'PM',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    country_code: 'VCT',
    country_code2: 'VC',
    currency_code: 'XCD',
    currency: 'East Caribbean Dollar',
  },
  {
    country: 'Samoa',
    country_code: 'WSM',
    country_code2: 'WS',
    currency_code: 'WST',
    currency: '-',
  },
  {
    country: 'San Marino',
    country_code: 'SMR',
    country_code2: 'SM',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Sao Tome and Principe',
    country_code: 'STP',
    country_code2: 'ST',
    currency_code: 'STN',
    currency: '-',
  },
  {
    country: 'Saudi Arabia',
    country_code: 'SAU',
    country_code2: 'SA',
    currency_code: 'SAR',
    currency: 'Saudi Arabia Riyal',
  },
  {
    country: 'Senegal',
    country_code: 'SEN',
    country_code2: 'SN',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Serbia and Montenegro',
    country_code: 'SCG',
    country_code2: 'CS',
    currency_code: 'RSD',
    currency: 'Serbia Dinar',
  },
  {
    country: 'Seychelles',
    country_code: 'SYC',
    country_code2: 'SC',
    currency_code: 'SCR',
    currency: 'Seychelles Rupee',
  },
  {
    country: 'Sierra Leone',
    country_code: 'SLE',
    country_code2: 'SL',
    currency_code: 'SLL',
    currency: '-',
  },
  {
    country: 'Singapore',
    country_code: 'SGP',
    country_code2: 'SG',
    currency_code: 'SGD',
    currency: 'Singapore Dollar',
  },
  {
    country: 'Slovakia',
    country_code: 'SVK',
    country_code2: 'SK',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Slovenia',
    country_code: 'SVN',
    country_code2: 'SI',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Solomon Islands',
    country_code: 'SLB',
    country_code2: 'SB',
    currency_code: 'SBD',
    currency: 'Solomon Islands Dollar',
  },
  {
    country: 'Somalia',
    country_code: 'SOM',
    country_code2: 'SO',
    currency_code: 'SOS',
    currency: 'Somalia Shilling',
  },
  {
    country: 'South Africa',
    country_code: 'ZAF',
    country_code2: 'ZA',
    currency_code: 'ZAR',
    currency: 'South Africa Rand',
  },
  {
    country: 'South Georgia and the South Sandwich Islands',
    country_code: 'SGS',
    country_code2: 'GS',
    currency_code: 'GBP',
    currency: 'United Kingdom Pound',
  },
  {
    country: 'South Korea',
    country_code: 'KOR',
    country_code2: 'KR',
    currency_code: 'KRW',
    currency: 'South Korean Won',
  },
  {
    country: 'Spain',
    country_code: 'ESP',
    country_code2: 'ES',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Sri Lanka',
    country_code: 'LKA',
    country_code2: 'LK',
    currency_code: 'LKR',
    currency: 'Sri Lanka Rupee',
  },
  {
    country: 'Sudan',
    country_code: 'SDN',
    country_code2: 'SD',
    currency_code: 'SDG',
    currency: '-',
  },
  {
    country: 'Suriname',
    country_code: 'SUR',
    country_code2: 'SR',
    currency_code: 'SRD',
    currency: 'Suriname Dollar',
  },
  {
    country: 'Svalbard and Jan Mayen',
    country_code: 'SJM',
    country_code2: 'SJ',
    currency_code: 'NOK',
    currency: 'Norway Krone',
  },
  {
    country: 'Swaziland',
    country_code: 'SWZ',
    country_code2: 'SZ',
    currency_code: 'SZL',
    currency: '-',
  },
  {
    country: 'Sweden',
    country_code: 'SWE',
    country_code2: 'SE',
    currency_code: 'SEK',
    currency: 'Sweden Krona',
  },
  {
    country: 'Switzerland',
    country_code: 'CHE',
    country_code2: 'CH',
    currency_code: 'CHF',
    currency: 'Switzerland Franc',
  },
  {
    country: 'Syria',
    country_code: 'SYR',
    country_code2: 'SY',
    currency_code: 'SYP',
    currency: 'Syria Pound',
  },
  {
    country: 'Taiwan',
    country_code: 'TWN',
    country_code2: 'TW',
    currency_code: 'TWD',
    currency: 'Taiwan New Dollar',
  },
  {
    country: 'Tajikistan',
    country_code: 'TJK',
    country_code2: 'TJ',
    currency_code: 'TJS',
    currency: '-',
  },
  {
    country: 'Tanzania',
    country_code: 'TZA',
    country_code2: 'TZ',
    currency_code: 'TZS',
    currency: '-',
  },
  {
    country: 'Thailand',
    country_code: 'THA',
    country_code2: 'TH',
    currency_code: 'THB',
    currency: 'Thailand Baht',
  },
  {
    country: 'Togo',
    country_code: 'TGO',
    country_code2: 'TG',
    currency_code: 'XOF',
    currency: '-',
  },
  {
    country: 'Tokelau',
    country_code: 'TKL',
    country_code2: 'TK',
    currency_code: 'NZD',
    currency: 'New Zealand Dollar',
  },
  {
    country: 'Tonga',
    country_code: 'TON',
    country_code2: 'TO',
    currency_code: 'TOP',
    currency: '-',
  },
  {
    country: 'Trinidad and Tobago',
    country_code: 'TTO',
    country_code2: 'TT',
    currency_code: 'TTD',
    currency: 'Trinidad and Tobago Dollar',
  },
  {
    country: 'Tunisia',
    country_code: 'TUN',
    country_code2: 'TN',
    currency_code: 'TND',
    currency: '-',
  },
  {
    country: 'Turkey',
    country_code: 'TUR',
    country_code2: 'TR',
    currency_code: 'TRY',
    currency: 'Turkey Lira',
  },
  {
    country: 'Turkmenistan',
    country_code: 'TKM',
    country_code2: 'TM',
    currency_code: 'TMT',
    currency: '-',
  },
  {
    country: 'Turks and Caicos Islands',
    country_code: 'TCA',
    country_code2: 'TC',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Tuvalu',
    country_code: 'TUV',
    country_code2: 'TV',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'U.S. Virgin Islands',
    country_code: 'VIR',
    country_code2: 'VI',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Uganda',
    country_code: 'UGA',
    country_code2: 'UG',
    currency_code: 'UGX',
    currency: '-',
  },
  {
    country: 'Ukraine',
    country_code: 'UKR',
    country_code2: 'UA',
    currency_code: 'UAH',
    currency: 'Ukraine Hryvnia',
  },
  {
    country: 'United Arab Emirates',
    country_code: 'ARE',
    country_code2: 'AE',
    currency_code: 'AED',
    currency: 'UAE-Dirham',
  },
  {
    country: 'United Kingdom',
    country_code: 'GBR',
    country_code2: 'GB',
    currency_code: 'GBP',
    currency: 'United Kingdom Pound',
  },
  {
    country: 'United States',
    country_code: 'USA',
    country_code2: 'US',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
  {
    country: 'Uruguay',
    country_code: 'URY',
    country_code2: 'UY',
    currency_code: 'UYU',
    currency: 'Uruguay Peso',
  },
  {
    country: 'Uzbekistan',
    country_code: 'UZB',
    country_code2: 'UZ',
    currency_code: 'UZS',
    currency: 'Uzbekistan Som',
  },
  {
    country: 'Vanuatu',
    country_code: 'VUT',
    country_code2: 'VU',
    currency_code: 'VUV',
    currency: '-',
  },
  {
    country: 'Vatican',
    country_code: 'VAT',
    country_code2: 'VA',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Venezuela',
    country_code: 'VEN',
    country_code2: 'VE',
    currency_code: 'VES',
    currency: '-',
  },
  {
    country: 'Vietnam',
    country_code: 'VNM',
    country_code2: 'VN',
    currency_code: 'VND',
    currency: 'Viet Nam Dong',
  },
  {
    country: 'Wallis and Futuna',
    country_code: 'WLF',
    country_code2: 'WF',
    currency_code: 'XPF',
    currency: '-',
  },
  {
    country: 'Western Sahara',
    country_code: 'ESH',
    country_code2: 'EH',
    currency_code: 'MAD',
    currency: '-',
  },
  {
    country: 'Yemen',
    country_code: 'YEM',
    country_code2: 'YE',
    currency_code: 'YER',
    currency: 'Yemen Rial',
  },
  {
    country: 'Zambia',
    country_code: 'ZMB',
    country_code2: 'ZM',
    currency_code: 'ZMW',
    currency: '-',
  },
  {
    country: 'Zimbabwe',
    country_code: 'ZWE',
    country_code2: 'ZW',
    currency_code: 'ZWL',
    currency: '-',
  },
  {
    country: 'ÅLand Islands',
    country_code: 'ALA',
    country_code2: 'AX',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Saint BarthÉLemy',
    country_code: 'BLM',
    country_code2: 'BL',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Curacao',
    country_code: 'CW',
    country_code2: 'CW',
    currency_code: 'ANG',
    currency: 'Netherlands Antilles Guilder',
  },
  {
    country: 'Guernsey',
    country_code: 'GGY',
    country_code2: 'GG',
    currency_code: 'GBP',
    currency: 'United Kingdom Pound',
  },
  {
    country: 'Isle Of Man',
    country_code: 'IMN',
    country_code2: 'IM',
    currency_code: 'GBP',
    currency: 'United Kingdom Pound',
  },
  {
    country: 'Jersey',
    country_code: 'JEY',
    country_code2: 'JE',
    currency_code: 'GBP',
    currency: 'United Kingdom Pound',
  },
  {
    country: 'Montenegro',
    country_code: 'MNE',
    country_code2: 'ME',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Saint Martin (French Part)',
    country_code: 'MAF',
    country_code2: 'MF',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Serbia',
    country_code: 'SRB',
    country_code2: 'RS',
    currency_code: 'RSD',
    currency: 'Serbia Dinar',
  },
  {
    country: 'South Sudan',
    country_code: 'SSD',
    country_code2: 'SS',
    currency_code: 'SSP',
    currency: '-',
  },
  {
    country: 'Sint Maarten (Dutch Part)',
    country_code: 'SXM',
    country_code2: 'SX',
    currency_code: 'ANG',
    currency: 'Netherlands Antilles Guilder',
  },
  {
    country: 'Kosovo',
    country_code: 'XKX',
    country_code2: 'XK',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Ascension Island',
    country_code: 'ASC',
    country_code2: 'AC',
    currency_code: 'SHP',
    currency: 'Saint Helena Pound',
  },
  {
    country: 'Canary Islands',
    country_code: null,
    country_code2: 'IC',
    currency_code: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Clipperton Island',
    country_code: 'CCK',
    country_code2: 'CC',
    currency_code: 'AUD',
    currency: 'Australia Dollar',
  },
  {
    country: 'Tristan da Cunha',
    country_code: null,
    country_code2: 'TA',
    currency_code: 'SHP',
    currency: 'Saint Helena Pound',
  },
  {
    country: 'U.S. Outlying Islands',
    country_code: 'UMI',
    country_code2: 'UM',
    currency_code: 'USD',
    currency: 'United States Dollar',
  },
];

const getCountryFromCurrency = (currency: string) =>
  countries.find((e) => e.currency_code === currency)?.country_code2;

const CountriesUtils = { getCountryFromCurrency };
export default CountriesUtils;
