export default {
  settingsMainPage: 'settings-main-page-component',
  homePage: 'home-page-component',
  selectPage: 'select-keys-page',
  signUp: 'signup-page',
  signIn: 'sign-in-page',
  input: 'password-input',
  inputConfirmation: 'password-input-confirmation',
  addAccountMain: 'add-account-page',
  transfersFundsPage: 'transfer-funds-page',
  walletItemList: 'wallet-item-list',
  userTokens: 'my-tokens',
  governancePage: 'governance-page',
  powerUpDownPage: 'power-up-page',
  buyCoinsPage: 'buy-coins-page',
  conversionPage: 'conversion-page',
  savingsPage: 'savings-page',
  delegationsPage: 'delegations-page',
  confirmationPage: 'confirmation-page',
  incomingOutgoingPage: 'incoming-outgoing-page',
  proxySuggestion: 'proxy-suggestion',
  addByKeysPage: 'add-by-keys-page',
  addByAuthPage: 'add-by-auth-page',
  tokensSettings: 'tokens-settings',
  tokensHistory: 'tokens-history',
  tokensTransfer: 'transfer-tokens-page',
  tokensOperationPage: 'tokens-operation-page',
  tokensFilter: 'tokens-filter',
  peoplePage: 'settings-account-sub-menu-page',
  tunePage: 'user-preferences-page',
  settingsPage: 'advanced-settings-page',
  infoPage: 'about-page',
  advanceSettings: {
    rpcNodes: 'rpc-nodes-page',
    autoLock: 'auto-lock-page',
    changePassword: 'change-password-page',
    link: 'keychainify-page',
    analytics: 'analytics-settings-page',
    importExport: 'import-export-preferences-page',
    clearAllData: 'clear-all-data-page',
  },
  account: {
    subMenu: {
      addAccount: {
        router: 'settings-add-account-router-page',
      },
      manageAccounts: 'settings-manage-account',
      createAccountsStepOne: 'settings-create-account-step-one',
    },
  },
  userPreferences: {
    authorizedOperations: 'authorized-operations-page',
    automatedTasks: 'automated-tasks-page',
  },
  whatsNew: 'whats-new-component',
};
