import { EvmTransactionType } from '@popup/evm/interfaces/evm-transactions.interface';
import {
  Chain,
  ChainType,
  EvmChain,
  HiveChain,
} from '@popup/multichain/interfaces/chains.interface';

export const defaultChainList: Chain[] = [
  {
    name: 'HIVE',
    type: ChainType.HIVE,
    logo: 'https://files.peakd.com/file/peakd-hive/cedricguillas/AJmv1BzrF6W3vKz8ah9GJVfnHzA9khi4QAn95cZHNsNpEnSWxoRK61yTPpQcRcX.svg',
    chainId: 'beeab0de00000000000000000000000000000000000000000000000000000000',
    mainTokens: {
      hbd: 'HBD',
      hive: 'HIVE',
      hp: 'HP',
    },
    rpcs: [],
    isPopular: true,
    active: true,
  } as HiveChain,
  {
    name: 'Ethereum',
    chainId: '0x1',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/ethereum.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: false,
    isEth: true,
    rpcs: [
      {
        url: 'https://ethereum-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    openSeaChainId: 'ethereum',
    active: true,
  } as EvmChain,
  {
    name: 'Sepolia',
    chainId: '0xaa36a7',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/ethereum.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: true,
    isEth: true,
    rpcs: [
      {
        url: 'https://ethereum-sepolia-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: false,
    active: true,
  } as EvmChain,
  {
    name: 'Avalanche C-Chain',
    chainId: '0xa86a',
    type: ChainType.EVM,
    logo: 'https://cdn.routescan.io/cdn/chains/avax/avax-icon.svg',
    mainToken: 'AVAX',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: false,
    isEth: false,
    rpcs: [
      {
        url: 'https://avalanche-c-chain-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    openSeaChainId: 'avalanche',
    active: true,
  } as EvmChain,
  {
    name: 'Avalanche Fuji',
    chainId: '0xa869',
    type: ChainType.EVM,
    logo: 'https://cdn.routescan.io/cdn/chains/avax/avax-icon.svg',
    mainToken: 'AVAX',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: true,
    isEth: false,
    rpcs: [
      {
        url: 'https://avalanche-fuji-c-chain-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    active: true,
  } as EvmChain,
  {
    name: 'Arbitrum One Nitro',
    chainId: '0xa4b1',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/arbitrum-one-nitro.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: false,
    isEth: false,
    rpcs: [
      {
        url: 'https://arbitrum-one-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    openSeaChainId: 'arbitrum',
    active: true,
  } as EvmChain,
  {
    name: 'Arbitrum Sepolia',
    chainId: '0x66eee',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/arbitrum-one-nitro.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: true,
    isEth: false,
    rpcs: [
      {
        url: 'https://arbitrum-sepolia-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    active: true,
  } as EvmChain,
  {
    name: 'Base',
    chainId: '0x2105',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/base.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: false,
    isEth: false,
    rpcs: [
      {
        url: 'https://base-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    openSeaChainId: 'base',
    active: true,
  } as EvmChain,
  {
    name: 'Base Sepolia',
    chainId: '0x14a34',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/base-sepolia.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: true,
    isEth: false,
    rpcs: [
      {
        url: 'https://base-sepolia-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    active: true,
  } as EvmChain,
  {
    name: 'OP Sepolia',
    chainId: '0xaa37dc',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/op-mainnet.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: true,
    isEth: false,
    rpcs: [
      {
        url: 'https://optimism-sepolia-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    active: true,
  } as EvmChain,
  {
    name: 'OP',
    chainId: '0xa',
    type: ChainType.EVM,
    logo: 'https://blockscout-icons.s3.us-east-1.amazonaws.com/op-mainnet.svg',
    mainToken: 'ETH',
    defaultTransactionType: EvmTransactionType.EIP_1559,
    testnet: false,
    isEth: false,
    rpcs: [
      {
        url: 'https://optimism-rpc.publicnode.com',
        isDefault: true,
      },
    ],
    isPopular: true,
    openSeaChainId: 'optimism',
    active: true,
  } as EvmChain,
];
