export enum MultichainScreen {
  HOME_PAGE = 'HOME_PAGE',

  CREATE_BLOCKCHAIN_PAGE = 'CREATE_BLOCKCHAIN_PAGE',
  SELECT_BLOCKCHAIN_PAGE = 'SELECT_BLOCKCHAIN_PAGE',

  BUY_COINS_PAGE = 'BUY_COINS_PAGE',
  CONFIRMATION_PAGE = 'CONFIRMATION_PAGE',

  ECOSYSTEM_PAGE = 'ECOSYSTEM_PAGE',

  SIGN_IN_ROUTER = 'SIGN_IN_ROUTER',
  SIGN_IN_PAGE = 'SIGN_IN_PAGE',
  SIGN_UP_PAGE = 'SIGN_UP_PAGE',
  RESET_PASSWORD_PAGE = 'RESET_PASSWORD_PAGE',

  TOKEN_SWAP_PAGE = 'TOKEN_SWAP_PAGE',
  TOKENS_SWAP_HISTORY = 'TOKENS_SWAP_HISTORY',
  TRANSFER_FUND_PAGE = 'TRANSFER_FUND_PAGE',

  //Settings
  SETTINGS_CHANGE_PASSWORD = 'SETTINGS_CHANGE_PASSWORD',
  SETTINGS_AUTO_LOCK = 'SETTINGS_AUTO_LOCK',
  SETTINGS_KEYCHAINIFY = 'SETTINGS_KEYCHAINIFY',
  SETTINGS_CLEAR_ALL_DATA = 'SETTINGS_CLEAR_ALL_DATA',
  SETTINGS_RPC_NODES = 'SETTINGS_RPC_NODES',
  SETTINGS_ABOUT = 'SETTINGS_ABOUT',
  SETTINGS_HELP = 'SETTINGS_HELP',
  SETTINGS_ANALYTICS = 'SETTINGS_ANALYTICS',
  SETTINGS_SHORTCUTS = 'SETTINGS_SHORTCUTS',
  SETTINGS_CONTACTS = 'SETTINGS_CONTACTS',
  SETTINGS_NETWORK = 'SETTINGS_NETWORK',
  SETTINGS_CONNECTED_DAPPS = 'SETTINGS_CONNECTED_DAPPS',
  SETTINGS_PREFERENCES_AND_DISPLAY = 'SETTINGS_PREFERENCES_AND_DISPLAY',
  SETTINGS_EVM = 'SETTINGS_EVM',
  SETTINGS_HIVE = 'SETTINGS_HIVE',

  UNDEFINED = 'UNDEFINED',
}
