export enum MultichainScreen {
  CREATE_BLOCKCHAIN_PAGE = 'CREATE_BLOCKCHAIN_PAGE',
  SELECT_BLOCKCHAIN_PAGE = 'SELECT_BLOCKCHAIN_PAGE',

  ECOSYSTEM_PAGE = 'ECOSYSTEM_PAGE',

  SIGN_IN_ROUTER = 'SIGN_IN_ROUTER',
  SIGN_IN_PAGE = 'SIGN_IN_PAGE',
  SIGN_UP_PAGE = 'SIGN_UP_PAGE',
  RESET_PASSWORD_PAGE = 'RESET_PASSWORD_PAGE',

  //Settings
  SETTINGS_CHANGE_PASSWORD = 'SETTINGS_CHANGE_PASSWORD',
  SETTINGS_AUTO_LOCK = 'SETTINGS_AUTO_LOCK',
  SETTINGS_KEYCHAINIFY = 'SETTINGS_KEYCHAINIFY',
  SETTINGS_CLEAR_ALL_DATA = 'SETTINGS_CLEAR_ALL_DATA',
  SETTINGS_RPC_NODES = 'SETTINGS_RPC_NODES',
  SETTINGS_ABOUT = 'SETTINGS_ABOUT',
  SETTINGS_HELP = 'SETTINGS_HELP',
  SETTINGS_ANALYTICS = 'SETTINGS_ANALYTICS',

  UNDEFINED = 'UNDEFINED',
}
