export enum EvmScreen {
  CREATE_EVM_WALLET = 'CREATE_EVM_WALLET',
  IMPORT_EVM_WALLET = 'IMPORT_EVM_WALLET',
  EVM_ADD_WALLET_MAIN = 'EVM_ADD_WALLET_MAIN',
  IMPORT_EVM_WALLET_CONFIRMATION = 'IMPORT_EVM_WALLET_CONFIRMATION',
  CREATE_EVM_WALLET_VERIFICATION = 'CREATE_EVM_WALLET_VERIFICATION',

  EVM_SETTINGS = 'EVM_SETTINGS',
  EVM_ADVANCED_SETTINGS = 'EVM_ADVANCED_SETTINGS',

  EVM_TOKEN_HISTORY = 'EVM_TOKEN_HISTORY',
  EVM_TRANSFER_RESULT_PAGE = 'EVM_TRANSFER_RESULT_PAGE',

  EVM_NFT_COLLECTION_PAGE = 'EVM_NFT_COLLECTION_PAGE',
  EVM_NFT_ALL_NFTS_PAGE = 'EVM_NFT_ALL_NFTS_PAGE',

  EVM_ACCOUNTS_SETTINGS = 'EVM_ACCOUNTS_SETTINGS',
}
