export enum SVGIcons {
  BLOCKCHAIN_AVALANCHE = 'blockchains/avalanche',
  BLOCKCHAIN_BNB = 'blockchains/bnb',
  BLOCKCHAIN_ETHEREUM = 'blockchains/ethereum',
  BLOCKCHAIN_POLYGON = 'blockchains/polygon',
  BLOCKCHAIN_HIVE = 'blockchains/hive',

  BOTTOM_BAR_BUY = 'bottom-bar/buy',
  BOTTOM_BAR_ECOSYSTEM = 'bottom-bar/ecosystem',
  BOTTOM_BAR_SEND = 'bottom-bar/send',
  BOTTOM_BAR_SWAPS = 'bottom-bar/swaps',

  BUY_BINANCE = 'buy/binance',
  BUY_GATEIO = 'buy/gateio',
  BUY_HUOBI = 'buy/huobi',
  BUY_IONOMY = 'buy/ionomy',
  BUY_MEXC = 'buy/mexc',
  BUY_TRANSAK = 'buy/transak',
  BUY_UPBIT = 'buy/upbit',

  CHECKBOX_CHECKED = 'checkbox/checked',

  EVM_ACCOUNT_ADD = 'evm-account/add-circle',
  EVM_ACCOUNT_EDIT = 'evm-account/edit-circle',

  EVM_GAS_FEE_DETAILS = 'evm-gas-fee/gas-fee-details',
  EVM_GAS_FEE_LOW = 'evm-gas-fee/gas-fee-low',
  EVM_GAS_FEE_MEDIUM = 'evm-gas-fee/gas-fee-medium',
  EVM_GAS_FEE_HIGH = 'evm-gas-fee/gas-fee-high',
  EVM_GAS_FEE_CUSTOM = 'evm-gas-fee/gas-fee-custom',
  EVM_GAS_FEE_SUGGESTED = 'evm-gas-fee/gas-fee-suggested',

  EVM_SMART_CONTRACT = 'evm-history/smart-contract',
  EVM_SMART_CONTRACT_CREATION = 'evm-history/smart-contract-creation',

  EVM_TRANSACTION_STATUS_PROCESSING = 'evm-tx-status/processing',
  EVM_TRANSACTION_STATUS_FINISHED = 'evm-tx-status/finished',
  EVM_TRANSACTION_STATUS_CANCELED = 'evm-tx-status/canceled',

  EVM_SETUP_IMAGE = 'evm-setup/coin-img',
  EVM_SETUP_DISPLAY_MNEMONIC = 'evm-setup/display-mnemonic',
  EVM_SETUP_COPY_MNEMONIC = 'evm-setup/copy-mnemonic',
  EVM_SETUP_HIDE_MNEMONIC = 'evm-setup/hide-mnemonic',

  FAVORITE_ACCOUNTS_EDIT = 'favorite-accounts/edit',
  FAVORITE_ACCOUNTS_DELETE = 'favorite-accounts/delete',
  FAVORITE_ACCOUNTS_CANCEL = 'favorite-accounts/cancel',
  FAVORITE_ACCOUNTS_SAVE = 'favorite-accounts/save',

  GLOBAL_ARROW = 'global/arrow',
  GLOBAL_DELETE = 'global/delete',
  GLOBAL_ERROR = 'global/error',
  GLOBAL_ADD_CIRCLE = 'global/add-circle',
  GLOBAL_EXPAND_COLLAPSE = 'global/expand-collapse',
  GLOBAL_WARNING = 'global/warning',
  GLOBAL_INFO = 'global/info',
  GLOBAL_CHECK = 'global/check',
  GLOBAL_TRIANGLE_ARROW = 'global/triangle-arrow',
  GLOBAL_EDIT = 'global/edit',

  GOVERNANCE_MY_WITNESS_DEACTIVATED = 'governance/my-witness/deactivated',
  GOVERNANCE_WITNESS_LINK = 'governance/witness-link',
  GOVERNANCE_WITNESS_UPVOTE_DOWNVOTE = 'governance/update-downvote-witness',
  GOVERNANCE_PROPOSAL_BUDGET = 'governance/proposal/budget',
  GOVERNANCE_PROPOSAL_DURATION = 'governance/proposal/duration',
  GOVERNANCE_PROPOSAL_EXPAND_COLLAPSE = 'governance/proposal/expand-collapse',
  GOVERNANCE_PROPOSAL_UPVOTE_VALUE = 'governance/proposal/upvote-value',
  GOVERNANCE_PROPOSAL_UPVOTE = 'governance/proposal/upvote',

  HIVE_ENGINE = 'wallet/hive-engine',
  WALLET_SETTINGS = 'wallet/settings',
  WALLET_SEARCH = 'wallet/search',

  INPUT_SHOW = 'input/show',
  INPUT_HIDE = 'input/hide',
  INPUT_MAX = 'input/max',
  INPUT_ENCRYPT = 'input/encrypt',
  INPUT_DECRYPT = 'input/decrypt',
  INPUT_SEARCH = 'input/search',
  INPUT_AT = 'input/at',
  INPUT_CLEAR = 'input/clear',

  KEYCHAIN_LOGO_SPLASHSCREEN = 'splashscreen/keychain-logo',
  KEYCHAIN_LOGO_ROUND = 'keychain-round-logo',
  KEYCHAIN_LOGO_ROUND_SMALL = 'keychain-round-logo-small',
  KEYCHAIN_FULL_LOGO = 'keychain-full-logo',

  MENU_BUTTON = 'top-bar/menu-button',
  MENU_ABOUT = 'menu/about',

  MENU_THEME_DARK = 'menu/theme/dark-theme',
  MENU_THEME_LIGHT = 'menu/theme/light-theme',

  MENU_ACCOUNTS = 'menu/accounts',
  MENU_ACCOUNTS_ADD_ACCOUNT = 'menu/accounts/add-account',
  MENU_ACCOUNTS_CREATE_ACCOUNT = 'menu/accounts/create-account',
  MENU_ACCOUNTS_EXPORT = 'menu/accounts/export',
  MENU_ACCOUNTS_MANAGE_ACCOUNTS = 'menu/accounts/manage-accounts',
  MENU_ACCOUNTS_MANAGE_AUTHORITIES = 'menu/accounts/manage-authorities',

  MENU_ADVANCED_SETTINGS = 'menu/advanced-settings',
  MENU_ADVANCED_SETTINGS_ANALYTICS = 'menu/advanced-settings/analytics',
  MENU_ADVANCED_SETTINGS_AUTO_LOCK = 'menu/advanced-settings/auto-lock',
  MENU_ADVANCED_SETTINGS_CHANGE_PASSWORD = 'menu/advanced-settings/change-password',
  MENU_ADVANCED_SETTINGS_CLEAR_ALL = 'menu/advanced-settings/clear-all',
  MENU_ADVANCED_SETTINGS_IMPORT_EXPORT = 'menu/advanced-settings/import-export-settings',
  MENU_ADVANCED_SETTINGS_KEYCHAINIFY = 'menu/advanced-settings/keychainify',
  MENU_ADVANCED_SETTINGS_LINK_LEDGER_DEVICE = 'menu/advanced-settings/link-ledger-device',
  MENU_ADVANCED_SETTINGS_RPC_NODE = 'menu/advanced-settings/rpc-nodes',
  MENU_ADVANCED_SETTINGS_IMPORT_SETTINGS = 'menu/advanced-settings/import-settings',
  MENU_ADVANCED_SETTINGS_EXPORT_SETTINGS = 'menu/advanced-settings/export-settings',

  MENU_TOKENS = 'menu/tokens',

  MENU_GOVERNANCE = 'menu/governance',
  MENU_LOGOUT = 'menu/logout',
  MENU_PLUGINS = 'menu/plugins',
  MENU_HELP = 'menu/help',

  MENU_SUPPORT = 'menu/help/support',
  MENU_TUTORIAL = 'menu/help/tutorial',

  MENU_USER_PREFERENCES_DETACH_EXTENSION = 'menu/user-preferences/detach',
  MENU_USER_PREFERENCES = 'menu/user-preferences',
  MENU_USER_PREFERENCES_OPERATIONS = 'menu/user-preferences/operations',
  MENU_USER_PREFERENCES_AUTOMATED_TASKS = 'menu/user-preferences/automated-tasks',
  MENU_USER_PREFERENCES_FAVORITE_ACCOUNTS = 'menu/user-preferences/favorite-accounts',
  MENU_USER_PREFERENCES_THEME = 'menu/user-preferences/theme',
  MENU_USER_PREFERENCES_NOTIFICATIONS = 'menu/user-preferences/notifications',
  MENU_USER_PREFERENCES_MULTISIG = 'menu/user-preferences/accounts-multisig',

  MENU_BOTTOM_BAR_DISCORD = 'menu/bottom-bar/discord',
  MENU_BOTTOM_BAR_HIVE = 'menu/bottom-bar/hive',
  MENU_BOTTOM_BAR_TWITTER = 'menu/bottom-bar/twitter',

  MENU_RPC_ADD_BUTTON = 'menu/rpc/add-button',
  MENU_RPC_CLOSE_BUTTON = 'menu/rpc/close-button',
  MENU_RPC_SAVE_BUTTON = 'menu/rpc/save-rpc-button',

  MESSAGE_ERROR = 'message/error',
  MESSAGE_WARNING = 'message/warning',
  MESSAGE_SUCCESS = 'message/success',

  NOTIFICATIONS_ADD = 'notifications/add',
  PORTOLIO = 'portfolio/portfolio',

  RESOURCE_ITEM_MANA = 'resources/mana',
  RESOURCE_ITEM_RC = 'resources/rc',
  RESOURCE_ITEM_SAVINGS = 'resources/savings',
  RESOURCE_ITEM_WALLET = 'resources/wallet',
  RESOURCE_ITEM_DELEGATION_INCOMING = 'resources/delegation-incoming',
  RESOURCE_ITEM_DELEGATION_OUTGOING = 'resources/delegation-outgoing',

  TOP_BAR_BACK_BTN = 'top-bar/back-button',
  TOP_BAR_CLAIM_REWARDS_BTN = 'top-bar/claim-rewards-button',
  TOP_BAR_CLOSE_BTN = 'top-bar/close-button',
  TOP_BAR_KEYCHAIN_LOGO = 'top-bar/keychain-logo',
  TOP_BAR_NOTIFICATION_BUTTON = 'top-bar/notification-button',

  SELECT_ARROW_DOWN = 'select/arrow-down',
  SELECT_ARROW_UP = 'select/arrow-up',
  SELECT_ACTIVE = 'select/active',
  SELECT_COPY = 'select/copy',
  SELECT_DRAG = 'select/drag',
  SELECT_DELETE = 'select/delete',
  SELECT_ADD = 'select/add-circle',

  SWAPS_SWITCH = 'swaps/swap-switch',
  SWAPS_HISTORY = 'swaps/history',
  SWAPS_ITEM = 'swaps/swap-item-icon',
  SWAPS_BETWEEN = 'swaps/swap-between',
  SWAPS_EXPAND = 'swaps/expand',
  SWAPS_ESTIMATE_REFRESH = 'swaps/estimate-refresh',
  SWAPS_HISTORY_REFRESH = 'swaps/history-refresh',
  SWAPS_STATUS_PROCESSING = 'swaps/swap-status/processing',
  SWAPS_STATUS_FINISHED = 'swaps/swap-status/finished',
  SWAPS_STATUS_CANCELED = 'swaps/swap-status/canceled',

  WALLET_HBD_LOGO = 'wallet/hbd-logo',
  WALLET_HIVE_LOGO = 'wallet/hive-logo',
  WALLET_HP_LOGO = 'wallet/hp-logo',
  WALLET_POWER_DOWN = 'wallet/hp/power-down',
  WALLET_POWER_UP = 'wallet/hive/power-up',
  WALLET_HP_DELEGATIONS = 'wallet/hp/hp-delegations',
  WALLET_RC_DELEGATIONS = 'wallet/hp/rc-delegations',
  WALLET_SAVINGS = 'wallet/common/savings',
  WALLET_CONVERT = 'wallet/common/convert',
  WALLET_SEND = 'wallet/common/send',
  WALLET_HISTORY_BUTTON = 'wallet/common/history',
  WALLET_TOKEN_DELEGATIONS = 'wallet/tokens/delegations',
  WALLET_TOKEN_STAKE = 'wallet/tokens/stake',
  WALLET_TOKEN_UNSTAKE = 'wallet/tokens/unstake',
  WALLET_TOKEN_GO_TO_DETAILED_PAGE = 'wallet/tokens/go-to-detailed-page',

  WALLET_TOKEN_PENDING_UNSTAKE_NEXT_TX = 'wallet/tokens/pending-unstake/next-tx',
  WALLET_TOKEN_PENDING_UNSTAKE_NEXT_TX_AMOUNT = 'wallet/tokens/pending-unstake/next-tx-amount',

  WALLET_HISTORY_FILTER_BUTTON = 'wallet/history/filter-button',
  WALLET_HISTORY_CLAIM_ACCOUNT = 'wallet/history/claim-account',
  WALLET_HISTORY_CLAIM_REWARDS = 'wallet/history/claim-rewards',
  WALLET_HISTORY_CONVERT = 'wallet/history/convert',
  WALLET_HISTORY_HP_DELEGATIONS = 'wallet/history/hp-delegations',
  WALLET_HISTORY_POWER_DOWN = 'wallet/history/power-down',
  WALLET_HISTORY_POWER_UP = 'wallet/history/power-up',
  WALLET_HISTORY_RC_DELEGATIONS = 'wallet/history/rc-delegations',
  WALLET_HISTORY_SAVINGS = 'wallet/history/savings',
  WALLET_HISTORY_TRANSFER = 'wallet/history/transfer',
  WALLET_HISTORY_TOKEN_DELEGATIONS = 'wallet/history/token-delegations',
  WALLET_HISTORY_STAKE = 'wallet/history/stake',
  WALLET_HISTORY_UNSTAKE = 'wallet/history/unstake',
  WALLET_HISTORY_EXPAND_COLLAPSE = 'wallet/history/expand-collapse',
  WALLET_HISTORY_TOP = 'wallet/history/back-to-top',

  // LOGOS
  BINANCE = 'binance',
  IONOMY = 'ionomy',
  GATEIO = 'gateio',
  HUOBI = 'huobi',
  MEXC = 'mexc-global',
  PROBIT = 'probit',
  TRANSAK = 'transak',
  UPBIT = 'upbit',
}
