export enum Icons {
  ACCOUNT = 'person',
  ACCOUNTS = 'people',
  ADD_ACCOUNT = 'person_add',
  ADD_CIRCLE = 'add_circle_outline',
  ANALYTICS = 'analytics',
  ARROW_CIRCLE_UP = 'arrow_circle_up',
  ARROW_DROPDOWN = 'arrow_drop_down',
  ARROW_UP = 'arrow_circle_up',
  ARROW_UPWARDS = 'arrow_upward',
  ARROW_DOWNWARDS = 'arrow_downward',
  AT = 'alternate_email',
  ATTACH_MONEY = 'attach_money',
  AUTO_LOCK = 'lock_clock',
  AUTOMATED_TASKS = 'hdr_auto',
  AUTHORIZED_OPERATIONS = 'rule',
  BACK = 'arrow_back',
  BUY = 'shopping_cart',
  CLAIM = 'redeem',
  CLEAR = 'clear',
  CLOSE = 'clear',
  CONVERT = 'currency_exchange',
  COPY = 'file_copy',
  CREATE_ACCOUNT = 'group_add',
  DELEGATIONS = 'swap_horiz',
  DELEGATIONS_RC = 'rc-delegation.svg',
  DELEGATIONS_HP = 'hp-delegation.svg',
  DELETE = 'delete',
  DISCORD = 'discord.svg',
  DONE = 'done',
  EDIT = 'edit',
  ERROR = 'error',
  EXPAND_MORE = 'expand_more',
  EXPORT = 'file_download',
  FAVORITE = 'favorite_border',
  FILTER = 'filter_alt',
  HIDDEN = 'visibility_off',
  HISTORY = 'history',
  HIVE = 'hive-brands.svg',
  INBOX = 'inbox',
  INFO = 'info',
  IMPORT = 'file_upload',
  IMPORT_EXPORT = 'import_export',
  KEY = 'key',
  LINK = 'link',
  LIST = 'list',
  LOCK = 'lock',
  LOGIN = 'login',
  LOGOUT = 'logout',
  MANAGE_ACCOUNTS = 'manage_accounts',
  MANAGE_AUTHORITIES = 'supervisor_account',
  MENU = 'menu',
  MORE_VERT = 'more_vert',
  OPEN_IN_NEW = 'open_in_new',
  PASSWORD = 'password',
  PREFERENCES = 'tune',
  REFRESH = 'refresh',
  RC = 'speed',
  RPC = 'settings_ethernet',
  SAVE = 'save',
  SAVINGS = 'savings',
  SEARCH = 'search',
  SETTINGS = 'settings',
  SEND = 'send',
  SHOW_CHART = 'show_chart',
  SUBMIT = 'input',
  SUPPORT = 'contact_support',
  TIMELAPSE = 'timelapse',
  TOKENS = 'generating_tokens',
  TWITTER = 'twitter.svg',
  USB = 'usb',
  VISIBLE = 'visibility',
  WARNING = 'warning',
  WITNESS_DISABLED = 'no_accounts',
}

import BUY from 'public/assets/images/buy.svg';
import CHAINS from 'public/assets/images/chains.svg';
import CLAIM_REWARDS from 'public/assets/images/claim-rewards.svg';
import HISTORY from 'public/assets/images/history.svg';
import HIVE_ENGINE from 'public/assets/images/hive-engine.svg';
import MENU from 'public/assets/images/menu.svg';
import RESOURCE_CREDITS from 'public/assets/images/resource-credit.svg';
import SELECT_ARROW_DOWN from 'public/assets/images/select-arrow-down.svg';
import SELECT_ARROW_UP from 'public/assets/images/select-arrow-up.svg';
import SEND from 'public/assets/images/send.svg';
import VOTING_MANA from 'public/assets/images/voting-mana.svg';

export const NewIcons = {
  BUY,
  CHAINS,
  CLAIM_REWARDS,
  HISTORY,
  HIVE_ENGINE,
  MENU,
  RESOURCE_CREDITS,
  SELECT_ARROW_DOWN,
  SELECT_ARROW_UP,
  SEND,
  VOTING_MANA,
};

export type IconType = string;
